name: fullstack-challenge
services:
    app:
        build:
            context: ./docker
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - by-the-pixel-network
        ports:
            - "80:80"
            - "6001:6001"
        volumes:
            - .:/var/www/html

    mysql:
        image: mysql:8.4.4
        networks:
            - by-the-pixel-network
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD"
                ]
            interval: 5s
            retries: 3
            timeout: 5s

    redis:
        image: redis:7.4.2-alpine
        networks:
            - by-the-pixel-network
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping || exit 1"]
            interval: 5s
            retries: 3
            timeout: 5s

volumes:
    mysql_data:
    redis_data:

networks:
    by-the-pixel-network:
        driver: bridge
