name: fullstack-challenge
services:
    app:
        build:
            context: ./docker
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html

    mysql:
        image: mysql:8.4.4
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: root
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
                ]
            retries: 3
            timeout: 5s

    redis:
        image: redis:7.4.2-alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping || exit 1"]
            retries: 3
            timeout: 5s

volumes:
    mysql_data:
    redis_data:

networks:
   by-the-pixel-network:
    driver: bridge
